name: Test JSON Payload
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: workflow_dispatch
jobs:
  test_json_payload:
    runs-on: ubuntu-latest
    env:
      STATUS: in progress
      START: '2023-09-14T01:35:05.767Z'
      FINISH: '2023-09-14T01:37:02.767Z'
    steps:
      - name: hello actions
        shell: bash
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: checkout actions
        uses: actions/checkout@v3
      - name: use node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: read json
        id: payload
        uses: actions/github-script@v6
        with:
          script: |
            try {
              const fs = require('fs');
              const jsonString = fs.readFileSync('./config/schema.json');
              const res = JSON.parse(jsonString);
              core.setOutput('obj', res);
            } catch (err) {
              core.error("Error while reading or parsing the JSON");
              core.setFailed(err);
            }
      - name: output json
        id: result
        uses: actions/github-script@v6
        env:
          OBJ: ${{toJson(steps.payload.outputs.obj)}}
        with:
          script: |
            const { OBJ } = process.env;
            core.info(`obj: ${OBJ});
